---
title: "HW4 Markdown"
output: beamer_presentation
date: "2022-12-05"
---

```{r libraries, include=FALSE}
library(tidyverse)
library(bunching)
```


```{r data}
l_2000 <- read_csv("~/Econ 352/HW2/HW4/SFLP_performance_2000.csv")
l_2007 <- read_csv("~/Econ 352/HW2/HW4/SFLP_performance_2007.csv")
```


```{r graph}
z <- nrow(l_2000)

l_2000g <- l_2000 %>%
  mutate(rate_gap = round((current_interest_rate - mortgagerate_30yr), 1)) %>%
  mutate(pre_pay = case_when(
    !is.na(zero_balance_date) ~ 1,
    is.na(zero_balance_date) ~ 0)) %>%
  group_by(rate_gap) %>%
  summarize(pct = n()/z, prob = sum(pre_pay)/n())
```

```{r graph}
ggplot(data = l_2000g, aes(x = rate_gap, y = pct)) +
  geom_smooth() + 
  geom_smooth(aes(y = prob), color = "red") +
  scale_y_continuous(sec.axis = dup_axis()) +
  labs(title = "Distribution (Blue) vs Hazard Rates (Red) by Rate Gap", x = "Rate Gap", y = "Percentage of Loans")
```
```{r pre shift}
l_2000g %>%
  filter(rate_gap >= -0.5) %>% 
  filter(rate_gap <= 2.0) %>% 
  mutate(product = pct*prob) %>%
  summarize(total_prob = sum(product))

```
```{r rates fall}
probs <- l_2000g %>%
  select(rate_gap, prob)

new_pcts <- l_2000g %>%
  mutate(rate_gap = rate_gap + 1) %>%
  select(rate_gap, pct)


dfm <- merge(probs, new_pcts, by="rate_gap")

dfm %>%
  mutate(product = pct*prob) %>%
  summarize(total_prob = sum(product))

```


```{r 2007}
z2 <- nrow(l_2007)

l_2007g <- l_2007 %>%
  mutate(rate_gap = round((current_interest_rate - mortgagerate_30yr), 1)) %>%
  mutate(pre_pay = case_when(
    !is.na(zero_balance_date) ~ 1,
    is.na(zero_balance_date) ~ 0)) %>%
  group_by(rate_gap) %>%
  summarize(pct = n()/z2, prob = sum(pre_pay)/n())
```

```{r}
ggplot(data = l_2007g, aes(x = rate_gap, y = pct)) +
  geom_smooth() + 
  geom_smooth(aes(y = prob), color = "red") +
  scale_y_continuous(sec.axis = dup_axis()) +
  labs(title = "Distribution (Blue) vs Hazard Rates (Red) by Rate Gap", x = "Rate Gap", y = "Percentage of Loans")
```



