---
title: "HW3 Markdown"
output: beamer_presentation
date: "2022-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(bunching)
```


```{r data}
loans <- read_csv("~/Econ 352/HW2/HW3/all_llma_nc.csv")
limits <- read_csv("~/Econ 352/HW2/HW3/conformingloanlimits.csv")
```

```{r q_1}
sapply(loans, class)

```
```{r q_2}
loans <- loans %>% 
 filter(year >= 1992 & year <= 2007,
         product_type == 10,
         original_term == 360 | original_term == 180,
         loan_type == 1,
         loan_purpose %in% c(1, 2, 3, 5)
         )
```


```{r q_3}
loans <- merge(loans, limits,by="year")
```


```{r q_4}
loans <- loans %>%
  mutate(deviation = log(original_balance) - log(conformingloanlimit)) %>% 
  filter(!is.na(deviation)) %>% 
  mutate(bin = floor(deviation * 100)) %>%
  filter(abs(bin) <= 100) %>%
  filter(!is.na(initial_interest_rate)) %>%
  na.omit()

```

```{r q_5}
bins <- loans %>%
  mutate(lower_bound = (deviation*200000) %/% 1000) %>%
  filter(abs(lower_bound) < 100)

```



```{r q_6}
total <- as.integer(count(loans))

bin_share <- bins %>%
  group_by(lower_bound) %>%
  summarize(share = n()/total, mean = mean(initial_interest_rate, na.rm = TRUE))

bin_share
```


```{r q_2.1}
ggplot(data = bin_share, aes(x=lower_bound, y = share)) +
  geom_bar(stat="identity") +
  labs(title = "Loan Size Density", y = "Fraction of Loans", 
       x = "Deviation from CLL")
#check % 2X
```
```{r q_2.2}
loans %>%
  filter(abs(original_balance - conformingloanlimit) < 100000) %>%
  mutate(lower_bound = (deviation*200000) %/% 1000) %>%
  head()
```


```{r q_2.3}
preBin = bin_share %>% 
  filter(lower_bound < 0)
preBinReg = lm(mean ~ lower_bound, preBin)

postBin = bin_share %>%
  filter(lower_bound > 0)
postBinReg = lm(mean ~ lower_bound, postBin) 

preRates = predict(preBinReg, data.frame(lower_bound=c(0)))/100
postRates = predict(postBinReg, data.frame(lower_bound=c(0)))/100

question3 <- loans%>% 
  mutate(shifted_dev = deviation + 1)

options(warn=-1)
bunchit(question3$shifted_dev, zstar=1, t0=preRates, t1=postRates, binwidth = 0.01, bins_l=200, bins_r=200, poly=13)
        
#Error message when notch=T included

```


