---
title: "HW3 Markdown"
output: beamer_presentation
date: "2022-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(usethis)
library(bunching)
```

```{r}
limits <- read_csv("~/Econ 352 HW/HW3/conformingloanlimits.csv")
```


```{r}
all_llma_nc <- read_csv("~/Econ 352 HW/HW3/all_llma_nc.csv")

```

```{r 1-2}

loans <- all_llma_nc %>% 
  filter(year >= 1992 & year <= 2007,
         product_type == 10,
         original_term == 360 | original_term == 180,
         loan_type == 1,
         loan_purpose %in% c(1, 2, 3, 5)
         )

head(loans)

```
```{r q_3}
loans <- merge(loans, limits,by="year")
```


```{r q_4}
loans <- loans %>%
  mutate(deviation = log(original_balance) - log(conformingloanlimit)) %>% 
  filter(!is.na(deviation)) %>% 
  mutate(bin = floor(deviation * 100)) %>%
  filter(abs(bin) <= 100) %>%
  filter(!is.na(initial_interest_rate)) %>%
  na.omit()
```


```{r 1.5}
bins <- loans %>% mutate(deviation_bin = )

head(bins)

```

```{r 1.6}

total <- as.integer(count(bins))

bin_share <- bins %>% 
  group_by(deviation_bin) %>% 
  summarize(share = n()/total,
            mean = mean(initial_interest_rate))

bin_share

```

```{r 2-2}

# Unclear if loans have to only be from 2003. R writeup says yes, Stata writeup doesn't say anything.

data1a <- loans %>%
  mutate(lower_bound = (deviation*200000) %/% 1000) %>%
  filter(abs(lower_bound) < 100,
         year == 2003)

total1a <- as.integer(count(data1a))

grouped1a <- data1a %>%
  group_by(lower_bound) %>%
  summarize(share = n()/total, mean = mean(initial_interest_rate, na.rm = TRUE))

# Otherwise just this

graph1a <- bin_share %>% 
  mutate(overlimit = case_when(lower_bound <= 0 ~ FALSE,
                        TRUE ~ TRUE))

head(graph1a)

ggplot(data = graph1a, aes(x=lower_bound, y = mean, color = overlimit)) +
  geom_point() +
  geom_smooth(method = 'lm', se = FALSE, linetype = 2) +
  geom_vline(linetype = 2, xintercept = 0) +
  labs(title = "Mean interest rate by loan size", y = "Interest rate", x = "Loan amount - conforming limit") +
  theme(legend.position = "none")


```
```{r}
question3 <- loans %>% mutate(
  shifted_dev = deviation + 1
)
```

```{r}
# Example 1: Kink with integration constraint correction
kink1 <- bunchit(z_vector = as.numeric(question3$shifted_dev), zstar = 1, binwidth = 50,
bins_l = 20, bins_r = 20, poly = 4, t0 = 0, t1 = .2,
p_b = TRUE, seed = 1)
```

